In [ ]:
# Numpy:-It is an multidimensional array library.
# we can able to store all sorts of data into One_Dimension,..2,3,4...!!!

In [1]:
# one-dimension
import numpy as np
a = np.array([1,2,3])
print(a)

[1 2 3]


In [2]:
# two-dimension
b = np.array([1.0,2.5,3.0],[1.5,3.0,3.5])
print(b)

TypeError: data type not understood

In [3]:
b = np.array([1,3,2],[1,3,2])
print(b)

TypeError: data type not understood

In [8]:
# Two tuples we considered it ...() and enclose it with []
# when we used a list we have to use [] and tuple ()
b = np.array([(1,2,3,4),(5,6,7,8)])
b.shape

(2, 4)

In [10]:
number = [9,8,7,6]
x = np.array(number)
x

array([9, 8, 7, 6])

In [12]:
# Builtin functions to create the arrays as per our requirement
# arrays of zero
array_of_zeros = np.zeros((2,2))
array_of_zeros

array([[0., 0.],
       [0., 0.]])

In [13]:
# array_of_ones
array_of_ones = np.ones((3,4))
array_of_ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
# how to change the datatype
array_of_ones_int = np.ones((3,4),dtype = np.int16)
array_of_ones_int

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int16)

In [15]:
# Empty array
empty_array = np.empty((2,3))
empty_array

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
# to generate identity matrix
array_eye = np.eye(3)
array_eye

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
#Numpy-   arange(start_value,stop_value,stepcount,dtype)
array_of_evens = np.arange(2,20,2)
array_of_evens

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])