In [3]:
import numpy as np

a = np.array([10,10,10])
b = np.array([5,5,5])

a + b

array([15, 15, 15])

In [4]:
a-b

array([5, 5, 5])

In [5]:
a * b

array([50, 50, 50])

In [6]:
a / b # whenever we are applying a divison,output will be in float data type and the default data type of numpy is float

array([2., 2., 2.])

In [7]:
a % b

array([0, 0, 0], dtype=int32)

In [8]:
a < 35

array([ True,  True,  True])

In [9]:
a < 9

array([False, False, False])

In [12]:
# modifying an array without creating a new one

a += 3
a

array([19, 19, 19])

In [15]:
# unary operators
ages = np.array([12,15,18,20])
print(ages.sum())
print(ages.min())
print(ages.max())

65
12
20
