In [3]:
# by using float values
import numpy as np

array_of_floats = np.arange(0,2,0.3)
array_of_floats

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [7]:
array_2d = np.array([(2,4,6),(3,5,7)])
array_2d

array([[2, 4, 6],
       [3, 5, 7]])

In [8]:
array_2d = np.array([(2,4,6),(3,5,7)])
array_2d.shape

(2, 3)

In [10]:
a =np.arange(6)
print(a) #1D
a.shape

[0 1 2 3 4 5]


(6,)

In [11]:
array_nd = np.arange(6).reshape(2,3)
array_nd

array([[0, 1, 2],
       [3, 4, 5]])

In [12]:
array_nd = np.arange(100).reshape(10,10)
array_nd

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [13]:
array_nd = np.arange(100).reshape(3,25)
array_nd

ValueError: cannot reshape array of size 100 into shape (3,25)

In [14]:
array_nd = np.arange(100).reshape(3,50)
array_nd

ValueError: cannot reshape array of size 100 into shape (3,50)

In [16]:
array_nd = np.arange(10).reshape(6,2)
print(array_nd)
array_nd.shape

ValueError: cannot reshape array of size 10 into shape (6,2)