In [1]:
import numpy as np

#Rows and Col Operations in 2d array:
#------> axis = 0 ------>cols
#------> axis = 1 ------>rows

numbers = np.arange(12).reshape(3,4)
numbers

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [2]:
# we need to calculate sum of cols only

numbers.sum(axis = 0)

array([12, 15, 18, 21])

In [3]:
#we need tocalculate sum of rows only

numbers.sum(axis = 1)

array([ 6, 22, 38])

In [6]:
# i want to find smallest value

numbers.min(axis = 0)

array([0, 1, 2, 3])

In [7]:
# i want to find highest value

numbers.max(axis = 0)

array([ 8,  9, 10, 11])

In [10]:
# statistical functions:

test_scores = np.array([32.32,56.98,21.52,44.32,55.63,13.25,43.47,43.34])
print("Mean information scores of the students:")
print(np.mean(test_scores))
print(np.median(test_scores))

Mean information scores of the students:
38.85375
43.405
